security:
    providers:
        user_db:
            entity: { class: App\Entity\User, property: token }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            #security: false
            logout: ~
            guard:
                provider: user_db
                authenticators:
                    - App\Security\LoginTokenAuthenticator
        main:
            anonymous: ~
            logout: ~
            guard:
                provider: user_db
                authenticators:
                    - App\Security\LoginTokenAuthenticator